TWITTER_CONSUMER_KEY: y07ViRb7Cewdfa0YbFAjg
TWITTER_CONSUMER_SECRET: FasvJf1KHhOjNHTEyCtoJYTQkhVF9VvI72E0tIwcI
AWS_S3_KEY: AKIAJTBSGXDPEIRQS5VQ
AWS_S3_SECRET: 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
AWS_S3_BUCKET: torapic-development
