development:
  adapter: sqlite3
  encoding: utf8
  database: db/torapic_development.sqlite3
  pool: 25

test:
  adapter: sqlite3
  encoding: utf8
  database: db/torapic_test.sqlite3
  pool: 25

# production:
#   encoding: utf8
#   adapter: postgresql
#   username: tjvdiyxhpkabci
#   port: 5432
#   host: ec2-54-225-101-4.compute-1.amazonaws.com
#   database: dc71njc6b5oivs
#   password: b5ipDINtlUJdz_ReeOb8GnTeum

production:
  adapter: mysql2
  encoding: utf8
  pool: 25
  host: localhost
  database: torapic_production
  username: torapic
  password: T1gkAXi5215G

# create database torapic_production;
# grant all on torapic_production.* to 'torapic'@'localhost' identified by 'T1gkAXi5215G';
