# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# for Production server,
# create database torapic_production
# grant all on torapic_production.* to 'torapic'@'localhost' identified by '5173102cf01e6f7c9176cd8724d8bc67';

development:
  adapter: mysql2
  encoding: utf8
  database: torapic_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: torapic_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  encoding: unicode
  adapter: postgresql
  username: tjvdiyxhpkabci
  port: 5432
  host: ec2-54-225-101-4.compute-1.amazonaws.com
  database: dc71njc6b5oivs
  password: b5ipDINtlUJdz_ReeOb8GnTeum
