# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# 
# for Production server,
# create database torapic_production
# grant all on torapic_production.* to 'torapic'@'localhost' identified by '5173102cf01e6f7c9176cd8724d8bc67';

development:
  adapter: sqlite3
  encoding: utf8
  database: db/torapic_development.sqlite3

test:
  adapter: sqlite3
  encoding: utf8
  database: db/torapic_test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: torapic_production
  pool: 5
  username: torapic
  password: 5173102cf01e6f7c9176cd8724d8bc67
  socket: /tmp/mysql.sock