#= require jquery.turbolinks
#= require jquery_ujs
#= require pickadate/picker
#= require pickadate/picker.date
#= require pickadate/picker.time
#= require dropzone
#= require jquery-waypoints/waypoints
#= require nprogress
#= require nprogress-turbolinks
#= require components/sidebar
#= require turbolinks
#= require_self
